### PR TITLE
Cypress 11 support with tests

### LINKED ISSUE #140: Update plugin to be compatible with Cypress 11
It would be nice if this was updated to support Cypress 11.

### PR DESCRIPTION
**Pull request by johnhwhite**
Like #141 but also runs tests against supported Cypress versions in CI.

Fixes #140

### CODE REVIEW

**Comment by javelinco** [comment]
Looking forward to seeing this get merged!!

**Comment by LouisGinger** [comment]
Is this repo being monitored by it's founders as PRs don't seem to be getting approved. Does this need forking?

**Comment by LouisGinger** [comment]
Nice one Ben

**Comment by spacedawwwg** [comment]
@bmordue Does the 1.0.0 release need a push to npm?

**Comment by sirLisko** [comment]
@spacedawwwg yes, I can see the release tag in github but not in npm :(

**Comment by bmordue** [comment]
For future reference, looks like commit message must include one of the semantic-release keywords (fix, feat etc) to trigger publishing to npm: https://github.com/semantic-release/semantic-release

**Pull request merged**
