### PR TITLE
Upgraded axe-core to 4.0.2

### PR DESCRIPTION
**Pull request by vnorekyan**
Addressing issue #58

### CODE REVIEW

**Comment by timfisher** [comment]
Is it possible to merge this please?

**Comment by Brynman** [comment]
We would also be very interested in this.

**Comment by vnorekyan** [comment]
> Is it possible to merge this please?

I don't have write access, so I can't merge this, can someone else with write access do that?

**Review by sapegin — COMMENTED** [review]
Thanks for the pull request!

I might be missing something but this is a development dependency, and peer dependencies already allow you to install and use any 4.x version. What am I missing here?

https://github.com/component-driven/cypress-axe/blob/61631c14a0190329cebc8f8ac9e8f81f1f1ce071/package.json#L19-L21

**Pull request closed without merging**
